### ISSUE TITLE
Cannot instantiate interface Snowdog\Menu\Api\MenuRepositoryInterface

### ISSUE THREAD

**Issue by samjaninf** [SnowdogApps/magento2-alpaca-theme#112]
Hi, after following your instructions to install this theme, I get the following error when I activate the theme in Magento. Any help would be appreciated.

````
2019/01/12 02:55:41 [error] 12991#0: *593 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate interface Snowdog\Menu\Api\MenuRepositoryInterface in /var/www/magento.xxxxxxxxxxxxxxxxx.com/htdocs/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php:50
Stack trace:
#0 /var/www/magento.xxxxxxxxxxxxxxxxx.com/htdocs/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Snowdog\\Menu\\Ap...')
#1 /var/www/magento.xxxxxxxxxxxxxxxxx.com/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(160): Magento\Framework\ObjectManager\ObjectManager->get('Snowdog\\Menu\\Ap...')
#2 /var/www/magento.xxxxxxxxxxxxxxxxx.com/htdocs/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(246): Magento\Framework\ObjectManager\Factory\AbstractFactory->resolveArgument(Array, 'Snowdog\\Menu\\Ap...', NULL, 'menuRepository', 'Snowdog\\Menu\\Bl...')
#3 /var/www/magento.xxxxxxxxxxxxxxxxx.com/htdocs/vendor/magento/framework/ObjectManager/Factory/D" while reading response header from upstream, client: xx.xx.xx.xx, server: magento.xxxxxxxxxxxxxxxxx.com, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9090", host: "magento.xxxxxxxxxxxxxxxxx.com"
````

**Comment by szafran89** [comment]
Hi @samjaninf, sorry for the delay
Did you solve this issue?

**Comment by samjaninf** [comment]
@szafran89  I have not solved this issue. It seemed that it could not find the Menu module you guys made but which was installed as a dependency.

**Comment by szafran89** [comment]
Yes the same thoughts, we recommended to use our menu as a dependency, if you want to get rid of this menu please update composer.json in your project ;)

**Comment by SiluntKnight** [comment]
I know this is closed but...@samjaninf I came across the same issue running these commands got it working for me

`bin/magento module:enable --all`
`bin/magento setup:upgrade`
`bin/magento setup:di:compile`
